opt_in_rules:
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - prohibited_super_call
  - explicit_init
disabled_rules:
  - overridden_super_call
  - todo
  - type_body_length
  - function_parameter_count
  - nesting
  - trailing_whitespace
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - prohibited_super_call
  - empty_parentheses_with_trailing_closure
  - line_length
excluded:
  - Carthage
  - Pods
  - R.generated.swift